name: Linux 5.0.0~rc1 bytecode

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: ./.github/workflows/common.yml
    with:
      compiler: 'ocaml-variants.5.0.0~rc1+options,ocaml-option-bytecode-only'
      timeout: 360
