name: Linux 5.00.0+trunk

on:
  pull_request:
  push:
  schedule:
    # Prime the caches every Monday
    - cron: 0 1 * * MON

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml 5.00.0+trunk
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ocaml-variants.5.00.0+trunk
          opam-repositories: |
            default: https://github.com/ocaml/opam-repository.git
            ocaml-beta-repository: https://github.com/ocaml/ocaml-beta-repository.git
          opam-depext: false

      - run: opam pin add -y dune git+https://github.com/patricoferris/dune\#5.00

      - run: opam install . --deps-only --with-test

      - run: opam exec -- dune runtest
