name: MacOSX 4.12.0+domains

on:
  pull_request:
  push:
  schedule:
    # Prime the caches every Monday
    - cron: 0 1 * * MON

jobs:
  build:
    strategy:
      matrix:
        os:
          - macos-latest
        ocaml-compiler:
          - 4.12.0+domains

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ocaml-variants.${{ matrix.ocaml-compiler }}
          opam-repositories: |
            multicore: https://github.com/ocaml-multicore/multicore-opam.git
            default: https://github.com/ocaml/opam-repository.git

      - name: pin latest domainslib
        run: opam pin domainslib --dev-repo

      - run: opam install . --deps-only --with-test

      - run: opam exec -- dune runtest
